// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/buildinfo.proto

package com.google.devtools.kythe.proto;

public final class Buildinfo {
  private Buildinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kythe.proto.BuildDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * For build tools such as Bazel, that assign names to buildable targets, the
     * name of the build target that generated this compilation.
     * </pre>
     *
     * <code>string build_target = 1;</code>
     */
    java.lang.String getBuildTarget();
    /**
     * <pre>
     * For build tools such as Bazel, that assign names to buildable targets, the
     * name of the build target that generated this compilation.
     * </pre>
     *
     * <code>string build_target = 1;</code>
     */
    com.google.protobuf.ByteString
        getBuildTargetBytes();

    /**
     * <pre>
     * If known, the name or mnemonic of the generating rule.
     * </pre>
     *
     * <code>string rule_type = 2;</code>
     */
    java.lang.String getRuleType();
    /**
     * <pre>
     * If known, the name or mnemonic of the generating rule.
     * </pre>
     *
     * <code>string rule_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getRuleTypeBytes();
  }
  /**
   * <pre>
   * Details from the build tool used in a CompilationUnit.
   * Its type is "kythe.io/proto/kythe.proto.BuildDetails".
   * </pre>
   *
   * Protobuf type {@code kythe.proto.BuildDetails}
   */
  public  static final class BuildDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kythe.proto.BuildDetails)
      BuildDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BuildDetails.newBuilder() to construct.
    private BuildDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuildDetails() {
      buildTarget_ = "";
      ruleType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BuildDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              buildTarget_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ruleType_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.Buildinfo.internal_static_kythe_proto_BuildDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.kythe.proto.Buildinfo.internal_static_kythe_proto_BuildDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.kythe.proto.Buildinfo.BuildDetails.class, com.google.devtools.kythe.proto.Buildinfo.BuildDetails.Builder.class);
    }

    public static final int BUILD_TARGET_FIELD_NUMBER = 1;
    private volatile java.lang.Object buildTarget_;
    /**
     * <pre>
     * For build tools such as Bazel, that assign names to buildable targets, the
     * name of the build target that generated this compilation.
     * </pre>
     *
     * <code>string build_target = 1;</code>
     */
    public java.lang.String getBuildTarget() {
      java.lang.Object ref = buildTarget_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildTarget_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * For build tools such as Bazel, that assign names to buildable targets, the
     * name of the build target that generated this compilation.
     * </pre>
     *
     * <code>string build_target = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBuildTargetBytes() {
      java.lang.Object ref = buildTarget_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildTarget_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RULE_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object ruleType_;
    /**
     * <pre>
     * If known, the name or mnemonic of the generating rule.
     * </pre>
     *
     * <code>string rule_type = 2;</code>
     */
    public java.lang.String getRuleType() {
      java.lang.Object ref = ruleType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * If known, the name or mnemonic of the generating rule.
     * </pre>
     *
     * <code>string rule_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRuleTypeBytes() {
      java.lang.Object ref = ruleType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBuildTargetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildTarget_);
      }
      if (!getRuleTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBuildTargetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildTarget_);
      }
      if (!getRuleTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.devtools.kythe.proto.Buildinfo.BuildDetails)) {
        return super.equals(obj);
      }
      com.google.devtools.kythe.proto.Buildinfo.BuildDetails other = (com.google.devtools.kythe.proto.Buildinfo.BuildDetails) obj;

      boolean result = true;
      result = result && getBuildTarget()
          .equals(other.getBuildTarget());
      result = result && getRuleType()
          .equals(other.getRuleType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILD_TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getBuildTarget().hashCode();
      hash = (37 * hash) + RULE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRuleType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.devtools.kythe.proto.Buildinfo.BuildDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Details from the build tool used in a CompilationUnit.
     * Its type is "kythe.io/proto/kythe.proto.BuildDetails".
     * </pre>
     *
     * Protobuf type {@code kythe.proto.BuildDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kythe.proto.BuildDetails)
        com.google.devtools.kythe.proto.Buildinfo.BuildDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.devtools.kythe.proto.Buildinfo.internal_static_kythe_proto_BuildDetails_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.devtools.kythe.proto.Buildinfo.internal_static_kythe_proto_BuildDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.devtools.kythe.proto.Buildinfo.BuildDetails.class, com.google.devtools.kythe.proto.Buildinfo.BuildDetails.Builder.class);
      }

      // Construct using com.google.devtools.kythe.proto.Buildinfo.BuildDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        buildTarget_ = "";

        ruleType_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.devtools.kythe.proto.Buildinfo.internal_static_kythe_proto_BuildDetails_descriptor;
      }

      public com.google.devtools.kythe.proto.Buildinfo.BuildDetails getDefaultInstanceForType() {
        return com.google.devtools.kythe.proto.Buildinfo.BuildDetails.getDefaultInstance();
      }

      public com.google.devtools.kythe.proto.Buildinfo.BuildDetails build() {
        com.google.devtools.kythe.proto.Buildinfo.BuildDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.devtools.kythe.proto.Buildinfo.BuildDetails buildPartial() {
        com.google.devtools.kythe.proto.Buildinfo.BuildDetails result = new com.google.devtools.kythe.proto.Buildinfo.BuildDetails(this);
        result.buildTarget_ = buildTarget_;
        result.ruleType_ = ruleType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.devtools.kythe.proto.Buildinfo.BuildDetails) {
          return mergeFrom((com.google.devtools.kythe.proto.Buildinfo.BuildDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.devtools.kythe.proto.Buildinfo.BuildDetails other) {
        if (other == com.google.devtools.kythe.proto.Buildinfo.BuildDetails.getDefaultInstance()) return this;
        if (!other.getBuildTarget().isEmpty()) {
          buildTarget_ = other.buildTarget_;
          onChanged();
        }
        if (!other.getRuleType().isEmpty()) {
          ruleType_ = other.ruleType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.devtools.kythe.proto.Buildinfo.BuildDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.devtools.kythe.proto.Buildinfo.BuildDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buildTarget_ = "";
      /**
       * <pre>
       * For build tools such as Bazel, that assign names to buildable targets, the
       * name of the build target that generated this compilation.
       * </pre>
       *
       * <code>string build_target = 1;</code>
       */
      public java.lang.String getBuildTarget() {
        java.lang.Object ref = buildTarget_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildTarget_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * For build tools such as Bazel, that assign names to buildable targets, the
       * name of the build target that generated this compilation.
       * </pre>
       *
       * <code>string build_target = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBuildTargetBytes() {
        java.lang.Object ref = buildTarget_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildTarget_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * For build tools such as Bazel, that assign names to buildable targets, the
       * name of the build target that generated this compilation.
       * </pre>
       *
       * <code>string build_target = 1;</code>
       */
      public Builder setBuildTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For build tools such as Bazel, that assign names to buildable targets, the
       * name of the build target that generated this compilation.
       * </pre>
       *
       * <code>string build_target = 1;</code>
       */
      public Builder clearBuildTarget() {
        
        buildTarget_ = getDefaultInstance().getBuildTarget();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For build tools such as Bazel, that assign names to buildable targets, the
       * name of the build target that generated this compilation.
       * </pre>
       *
       * <code>string build_target = 1;</code>
       */
      public Builder setBuildTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildTarget_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ruleType_ = "";
      /**
       * <pre>
       * If known, the name or mnemonic of the generating rule.
       * </pre>
       *
       * <code>string rule_type = 2;</code>
       */
      public java.lang.String getRuleType() {
        java.lang.Object ref = ruleType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ruleType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * If known, the name or mnemonic of the generating rule.
       * </pre>
       *
       * <code>string rule_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRuleTypeBytes() {
        java.lang.Object ref = ruleType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ruleType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * If known, the name or mnemonic of the generating rule.
       * </pre>
       *
       * <code>string rule_type = 2;</code>
       */
      public Builder setRuleType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ruleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If known, the name or mnemonic of the generating rule.
       * </pre>
       *
       * <code>string rule_type = 2;</code>
       */
      public Builder clearRuleType() {
        
        ruleType_ = getDefaultInstance().getRuleType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If known, the name or mnemonic of the generating rule.
       * </pre>
       *
       * <code>string rule_type = 2;</code>
       */
      public Builder setRuleTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ruleType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kythe.proto.BuildDetails)
    }

    // @@protoc_insertion_point(class_scope:kythe.proto.BuildDetails)
    private static final com.google.devtools.kythe.proto.Buildinfo.BuildDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.devtools.kythe.proto.Buildinfo.BuildDetails();
    }

    public static com.google.devtools.kythe.proto.Buildinfo.BuildDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildDetails>
        PARSER = new com.google.protobuf.AbstractParser<BuildDetails>() {
      public BuildDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuildDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildDetails> getParserForType() {
      return PARSER;
    }

    public com.google.devtools.kythe.proto.Buildinfo.BuildDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kythe_proto_BuildDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kythe_proto_BuildDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033kythe/proto/buildinfo.proto\022\013kythe.pro" +
      "to\"7\n\014BuildDetails\022\024\n\014build_target\030\001 \001(\t" +
      "\022\021\n\trule_type\030\002 \001(\tB!\n\037com.google.devtoo" +
      "ls.kythe.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kythe_proto_BuildDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kythe_proto_BuildDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kythe_proto_BuildDetails_descriptor,
        new java.lang.String[] { "BuildTarget", "RuleType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
