// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/explore.proto

package com.google.devtools.kythe.proto;

/**
 * <pre>
 * Requests the functions that call the specified function.
 * </pre>
 *
 * Protobuf type {@code kythe.proto.CallersRequest}
 */
public  final class CallersRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kythe.proto.CallersRequest)
    CallersRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallersRequest.newBuilder() to construct.
  private CallersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallersRequest() {
    functionTicket_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallersRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            functionTicket_ = s;
            break;
          }
          case 18: {
            com.google.devtools.kythe.proto.NodeFilter.Builder subBuilder = null;
            if (nodeFilter_ != null) {
              subBuilder = nodeFilter_.toBuilder();
            }
            nodeFilter_ = input.readMessage(com.google.devtools.kythe.proto.NodeFilter.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nodeFilter_);
              nodeFilter_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_CallersRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_CallersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.kythe.proto.CallersRequest.class, com.google.devtools.kythe.proto.CallersRequest.Builder.class);
  }

  public static final int FUNCTION_TICKET_FIELD_NUMBER = 1;
  private volatile java.lang.Object functionTicket_;
  /**
   * <code>string function_ticket = 1;</code>
   */
  public java.lang.String getFunctionTicket() {
    java.lang.Object ref = functionTicket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      functionTicket_ = s;
      return s;
    }
  }
  /**
   * <code>string function_ticket = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFunctionTicketBytes() {
    java.lang.Object ref = functionTicket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      functionTicket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_FILTER_FIELD_NUMBER = 2;
  private com.google.devtools.kythe.proto.NodeFilter nodeFilter_;
  /**
   * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
   */
  public boolean hasNodeFilter() {
    return nodeFilter_ != null;
  }
  /**
   * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
   */
  public com.google.devtools.kythe.proto.NodeFilter getNodeFilter() {
    return nodeFilter_ == null ? com.google.devtools.kythe.proto.NodeFilter.getDefaultInstance() : nodeFilter_;
  }
  /**
   * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
   */
  public com.google.devtools.kythe.proto.NodeFilterOrBuilder getNodeFilterOrBuilder() {
    return getNodeFilter();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFunctionTicketBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, functionTicket_);
    }
    if (nodeFilter_ != null) {
      output.writeMessage(2, getNodeFilter());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFunctionTicketBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, functionTicket_);
    }
    if (nodeFilter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNodeFilter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.kythe.proto.CallersRequest)) {
      return super.equals(obj);
    }
    com.google.devtools.kythe.proto.CallersRequest other = (com.google.devtools.kythe.proto.CallersRequest) obj;

    boolean result = true;
    result = result && getFunctionTicket()
        .equals(other.getFunctionTicket());
    result = result && (hasNodeFilter() == other.hasNodeFilter());
    if (hasNodeFilter()) {
      result = result && getNodeFilter()
          .equals(other.getNodeFilter());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FUNCTION_TICKET_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionTicket().hashCode();
    if (hasNodeFilter()) {
      hash = (37 * hash) + NODE_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getNodeFilter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.CallersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.kythe.proto.CallersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Requests the functions that call the specified function.
   * </pre>
   *
   * Protobuf type {@code kythe.proto.CallersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kythe.proto.CallersRequest)
      com.google.devtools.kythe.proto.CallersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_CallersRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_CallersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.kythe.proto.CallersRequest.class, com.google.devtools.kythe.proto.CallersRequest.Builder.class);
    }

    // Construct using com.google.devtools.kythe.proto.CallersRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      functionTicket_ = "";

      if (nodeFilterBuilder_ == null) {
        nodeFilter_ = null;
      } else {
        nodeFilter_ = null;
        nodeFilterBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_CallersRequest_descriptor;
    }

    public com.google.devtools.kythe.proto.CallersRequest getDefaultInstanceForType() {
      return com.google.devtools.kythe.proto.CallersRequest.getDefaultInstance();
    }

    public com.google.devtools.kythe.proto.CallersRequest build() {
      com.google.devtools.kythe.proto.CallersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.devtools.kythe.proto.CallersRequest buildPartial() {
      com.google.devtools.kythe.proto.CallersRequest result = new com.google.devtools.kythe.proto.CallersRequest(this);
      result.functionTicket_ = functionTicket_;
      if (nodeFilterBuilder_ == null) {
        result.nodeFilter_ = nodeFilter_;
      } else {
        result.nodeFilter_ = nodeFilterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.kythe.proto.CallersRequest) {
        return mergeFrom((com.google.devtools.kythe.proto.CallersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.kythe.proto.CallersRequest other) {
      if (other == com.google.devtools.kythe.proto.CallersRequest.getDefaultInstance()) return this;
      if (!other.getFunctionTicket().isEmpty()) {
        functionTicket_ = other.functionTicket_;
        onChanged();
      }
      if (other.hasNodeFilter()) {
        mergeNodeFilter(other.getNodeFilter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.kythe.proto.CallersRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.kythe.proto.CallersRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object functionTicket_ = "";
    /**
     * <code>string function_ticket = 1;</code>
     */
    public java.lang.String getFunctionTicket() {
      java.lang.Object ref = functionTicket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionTicket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string function_ticket = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionTicketBytes() {
      java.lang.Object ref = functionTicket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionTicket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string function_ticket = 1;</code>
     */
    public Builder setFunctionTicket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      functionTicket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string function_ticket = 1;</code>
     */
    public Builder clearFunctionTicket() {
      
      functionTicket_ = getDefaultInstance().getFunctionTicket();
      onChanged();
      return this;
    }
    /**
     * <code>string function_ticket = 1;</code>
     */
    public Builder setFunctionTicketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      functionTicket_ = value;
      onChanged();
      return this;
    }

    private com.google.devtools.kythe.proto.NodeFilter nodeFilter_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.NodeFilter, com.google.devtools.kythe.proto.NodeFilter.Builder, com.google.devtools.kythe.proto.NodeFilterOrBuilder> nodeFilterBuilder_;
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public boolean hasNodeFilter() {
      return nodeFilterBuilder_ != null || nodeFilter_ != null;
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public com.google.devtools.kythe.proto.NodeFilter getNodeFilter() {
      if (nodeFilterBuilder_ == null) {
        return nodeFilter_ == null ? com.google.devtools.kythe.proto.NodeFilter.getDefaultInstance() : nodeFilter_;
      } else {
        return nodeFilterBuilder_.getMessage();
      }
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public Builder setNodeFilter(com.google.devtools.kythe.proto.NodeFilter value) {
      if (nodeFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nodeFilter_ = value;
        onChanged();
      } else {
        nodeFilterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public Builder setNodeFilter(
        com.google.devtools.kythe.proto.NodeFilter.Builder builderForValue) {
      if (nodeFilterBuilder_ == null) {
        nodeFilter_ = builderForValue.build();
        onChanged();
      } else {
        nodeFilterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public Builder mergeNodeFilter(com.google.devtools.kythe.proto.NodeFilter value) {
      if (nodeFilterBuilder_ == null) {
        if (nodeFilter_ != null) {
          nodeFilter_ =
            com.google.devtools.kythe.proto.NodeFilter.newBuilder(nodeFilter_).mergeFrom(value).buildPartial();
        } else {
          nodeFilter_ = value;
        }
        onChanged();
      } else {
        nodeFilterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public Builder clearNodeFilter() {
      if (nodeFilterBuilder_ == null) {
        nodeFilter_ = null;
        onChanged();
      } else {
        nodeFilter_ = null;
        nodeFilterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public com.google.devtools.kythe.proto.NodeFilter.Builder getNodeFilterBuilder() {
      
      onChanged();
      return getNodeFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    public com.google.devtools.kythe.proto.NodeFilterOrBuilder getNodeFilterOrBuilder() {
      if (nodeFilterBuilder_ != null) {
        return nodeFilterBuilder_.getMessageOrBuilder();
      } else {
        return nodeFilter_ == null ?
            com.google.devtools.kythe.proto.NodeFilter.getDefaultInstance() : nodeFilter_;
      }
    }
    /**
     * <code>.kythe.proto.NodeFilter node_filter = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.NodeFilter, com.google.devtools.kythe.proto.NodeFilter.Builder, com.google.devtools.kythe.proto.NodeFilterOrBuilder> 
        getNodeFilterFieldBuilder() {
      if (nodeFilterBuilder_ == null) {
        nodeFilterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.kythe.proto.NodeFilter, com.google.devtools.kythe.proto.NodeFilter.Builder, com.google.devtools.kythe.proto.NodeFilterOrBuilder>(
                getNodeFilter(),
                getParentForChildren(),
                isClean());
        nodeFilter_ = null;
      }
      return nodeFilterBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kythe.proto.CallersRequest)
  }

  // @@protoc_insertion_point(class_scope:kythe.proto.CallersRequest)
  private static final com.google.devtools.kythe.proto.CallersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.kythe.proto.CallersRequest();
  }

  public static com.google.devtools.kythe.proto.CallersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallersRequest>
      PARSER = new com.google.protobuf.AbstractParser<CallersRequest>() {
    public CallersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallersRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallersRequest> getParserForType() {
    return PARSER;
  }

  public com.google.devtools.kythe.proto.CallersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

