// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/xref.proto

package com.google.devtools.kythe.proto;

public interface DocumentationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kythe.proto.DocumentationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Semantic tickets about which documentation is sought.
   * </pre>
   *
   * <code>repeated string ticket = 1;</code>
   */
  java.util.List<java.lang.String>
      getTicketList();
  /**
   * <pre>
   * Semantic tickets about which documentation is sought.
   * </pre>
   *
   * <code>repeated string ticket = 1;</code>
   */
  int getTicketCount();
  /**
   * <pre>
   * Semantic tickets about which documentation is sought.
   * </pre>
   *
   * <code>repeated string ticket = 1;</code>
   */
  java.lang.String getTicket(int index);
  /**
   * <pre>
   * Semantic tickets about which documentation is sought.
   * </pre>
   *
   * <code>repeated string ticket = 1;</code>
   */
  com.google.protobuf.ByteString
      getTicketBytes(int index);

  /**
   * <pre>
   * A collection of filter globs that specify which facts (by name) should be
   * returned for each node.  If filter is empty or unset, no node facts are
   * returned. The filter applies to ALL documented and linked nodes.
   * See EdgesRequest (graph.proto) for the format of the filter globs.
   * </pre>
   *
   * <code>repeated string filter = 2;</code>
   */
  java.util.List<java.lang.String>
      getFilterList();
  /**
   * <pre>
   * A collection of filter globs that specify which facts (by name) should be
   * returned for each node.  If filter is empty or unset, no node facts are
   * returned. The filter applies to ALL documented and linked nodes.
   * See EdgesRequest (graph.proto) for the format of the filter globs.
   * </pre>
   *
   * <code>repeated string filter = 2;</code>
   */
  int getFilterCount();
  /**
   * <pre>
   * A collection of filter globs that specify which facts (by name) should be
   * returned for each node.  If filter is empty or unset, no node facts are
   * returned. The filter applies to ALL documented and linked nodes.
   * See EdgesRequest (graph.proto) for the format of the filter globs.
   * </pre>
   *
   * <code>repeated string filter = 2;</code>
   */
  java.lang.String getFilter(int index);
  /**
   * <pre>
   * A collection of filter globs that specify which facts (by name) should be
   * returned for each node.  If filter is empty or unset, no node facts are
   * returned. The filter applies to ALL documented and linked nodes.
   * See EdgesRequest (graph.proto) for the format of the filter globs.
   * </pre>
   *
   * <code>repeated string filter = 2;</code>
   */
  com.google.protobuf.ByteString
      getFilterBytes(int index);

  /**
   * <pre>
   * If set, this DocumentationRequest will return documents for the requested
   * tickets as well as their immediate semantic descendants.
   * </pre>
   *
   * <code>bool include_children = 3;</code>
   */
  boolean getIncludeChildren();
}
