// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/common.proto

package com.google.devtools.kythe.proto;

public interface FactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kythe.proto.common.Fact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bytes value = 2;</code>
   */
  com.google.protobuf.ByteString getValue();
}
