// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/explore.proto

package com.google.devtools.kythe.proto;

/**
 * <pre>
 * If the RPC request does not specify otherwise, sucessors and predecessors
 * are both populated.
 * </pre>
 *
 * Protobuf type {@code kythe.proto.GraphNode}
 */
public  final class GraphNode extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kythe.proto.GraphNode)
    GraphNodeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GraphNode.newBuilder() to construct.
  private GraphNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GraphNode() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GraphNode(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.devtools.kythe.proto.NodeData.Builder subBuilder = null;
            if (nodeData_ != null) {
              subBuilder = nodeData_.toBuilder();
            }
            nodeData_ = input.readMessage(com.google.devtools.kythe.proto.NodeData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nodeData_);
              nodeData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.devtools.kythe.proto.Tickets.Builder subBuilder = null;
            if (predecessors_ != null) {
              subBuilder = predecessors_.toBuilder();
            }
            predecessors_ = input.readMessage(com.google.devtools.kythe.proto.Tickets.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(predecessors_);
              predecessors_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.devtools.kythe.proto.Tickets.Builder subBuilder = null;
            if (successors_ != null) {
              subBuilder = successors_.toBuilder();
            }
            successors_ = input.readMessage(com.google.devtools.kythe.proto.Tickets.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(successors_);
              successors_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_GraphNode_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_GraphNode_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.kythe.proto.GraphNode.class, com.google.devtools.kythe.proto.GraphNode.Builder.class);
  }

  public static final int NODE_DATA_FIELD_NUMBER = 1;
  private com.google.devtools.kythe.proto.NodeData nodeData_;
  /**
   * <code>.kythe.proto.NodeData node_data = 1;</code>
   */
  public boolean hasNodeData() {
    return nodeData_ != null;
  }
  /**
   * <code>.kythe.proto.NodeData node_data = 1;</code>
   */
  public com.google.devtools.kythe.proto.NodeData getNodeData() {
    return nodeData_ == null ? com.google.devtools.kythe.proto.NodeData.getDefaultInstance() : nodeData_;
  }
  /**
   * <code>.kythe.proto.NodeData node_data = 1;</code>
   */
  public com.google.devtools.kythe.proto.NodeDataOrBuilder getNodeDataOrBuilder() {
    return getNodeData();
  }

  public static final int PREDECESSORS_FIELD_NUMBER = 2;
  private com.google.devtools.kythe.proto.Tickets predecessors_;
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by incoming edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets predecessors = 2;</code>
   */
  public boolean hasPredecessors() {
    return predecessors_ != null;
  }
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by incoming edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets predecessors = 2;</code>
   */
  public com.google.devtools.kythe.proto.Tickets getPredecessors() {
    return predecessors_ == null ? com.google.devtools.kythe.proto.Tickets.getDefaultInstance() : predecessors_;
  }
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by incoming edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets predecessors = 2;</code>
   */
  public com.google.devtools.kythe.proto.TicketsOrBuilder getPredecessorsOrBuilder() {
    return getPredecessors();
  }

  public static final int SUCCESSORS_FIELD_NUMBER = 3;
  private com.google.devtools.kythe.proto.Tickets successors_;
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by outgoing edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets successors = 3;</code>
   */
  public boolean hasSuccessors() {
    return successors_ != null;
  }
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by outgoing edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets successors = 3;</code>
   */
  public com.google.devtools.kythe.proto.Tickets getSuccessors() {
    return successors_ == null ? com.google.devtools.kythe.proto.Tickets.getDefaultInstance() : successors_;
  }
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by outgoing edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets successors = 3;</code>
   */
  public com.google.devtools.kythe.proto.TicketsOrBuilder getSuccessorsOrBuilder() {
    return getSuccessors();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nodeData_ != null) {
      output.writeMessage(1, getNodeData());
    }
    if (predecessors_ != null) {
      output.writeMessage(2, getPredecessors());
    }
    if (successors_ != null) {
      output.writeMessage(3, getSuccessors());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nodeData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNodeData());
    }
    if (predecessors_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPredecessors());
    }
    if (successors_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSuccessors());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.kythe.proto.GraphNode)) {
      return super.equals(obj);
    }
    com.google.devtools.kythe.proto.GraphNode other = (com.google.devtools.kythe.proto.GraphNode) obj;

    boolean result = true;
    result = result && (hasNodeData() == other.hasNodeData());
    if (hasNodeData()) {
      result = result && getNodeData()
          .equals(other.getNodeData());
    }
    result = result && (hasPredecessors() == other.hasPredecessors());
    if (hasPredecessors()) {
      result = result && getPredecessors()
          .equals(other.getPredecessors());
    }
    result = result && (hasSuccessors() == other.hasSuccessors());
    if (hasSuccessors()) {
      result = result && getSuccessors()
          .equals(other.getSuccessors());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNodeData()) {
      hash = (37 * hash) + NODE_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getNodeData().hashCode();
    }
    if (hasPredecessors()) {
      hash = (37 * hash) + PREDECESSORS_FIELD_NUMBER;
      hash = (53 * hash) + getPredecessors().hashCode();
    }
    if (hasSuccessors()) {
      hash = (37 * hash) + SUCCESSORS_FIELD_NUMBER;
      hash = (53 * hash) + getSuccessors().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.GraphNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.kythe.proto.GraphNode prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * If the RPC request does not specify otherwise, sucessors and predecessors
   * are both populated.
   * </pre>
   *
   * Protobuf type {@code kythe.proto.GraphNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kythe.proto.GraphNode)
      com.google.devtools.kythe.proto.GraphNodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_GraphNode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_GraphNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.kythe.proto.GraphNode.class, com.google.devtools.kythe.proto.GraphNode.Builder.class);
    }

    // Construct using com.google.devtools.kythe.proto.GraphNode.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (nodeDataBuilder_ == null) {
        nodeData_ = null;
      } else {
        nodeData_ = null;
        nodeDataBuilder_ = null;
      }
      if (predecessorsBuilder_ == null) {
        predecessors_ = null;
      } else {
        predecessors_ = null;
        predecessorsBuilder_ = null;
      }
      if (successorsBuilder_ == null) {
        successors_ = null;
      } else {
        successors_ = null;
        successorsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_GraphNode_descriptor;
    }

    public com.google.devtools.kythe.proto.GraphNode getDefaultInstanceForType() {
      return com.google.devtools.kythe.proto.GraphNode.getDefaultInstance();
    }

    public com.google.devtools.kythe.proto.GraphNode build() {
      com.google.devtools.kythe.proto.GraphNode result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.devtools.kythe.proto.GraphNode buildPartial() {
      com.google.devtools.kythe.proto.GraphNode result = new com.google.devtools.kythe.proto.GraphNode(this);
      if (nodeDataBuilder_ == null) {
        result.nodeData_ = nodeData_;
      } else {
        result.nodeData_ = nodeDataBuilder_.build();
      }
      if (predecessorsBuilder_ == null) {
        result.predecessors_ = predecessors_;
      } else {
        result.predecessors_ = predecessorsBuilder_.build();
      }
      if (successorsBuilder_ == null) {
        result.successors_ = successors_;
      } else {
        result.successors_ = successorsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.kythe.proto.GraphNode) {
        return mergeFrom((com.google.devtools.kythe.proto.GraphNode)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.kythe.proto.GraphNode other) {
      if (other == com.google.devtools.kythe.proto.GraphNode.getDefaultInstance()) return this;
      if (other.hasNodeData()) {
        mergeNodeData(other.getNodeData());
      }
      if (other.hasPredecessors()) {
        mergePredecessors(other.getPredecessors());
      }
      if (other.hasSuccessors()) {
        mergeSuccessors(other.getSuccessors());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.kythe.proto.GraphNode parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.kythe.proto.GraphNode) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.devtools.kythe.proto.NodeData nodeData_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.NodeData, com.google.devtools.kythe.proto.NodeData.Builder, com.google.devtools.kythe.proto.NodeDataOrBuilder> nodeDataBuilder_;
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public boolean hasNodeData() {
      return nodeDataBuilder_ != null || nodeData_ != null;
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public com.google.devtools.kythe.proto.NodeData getNodeData() {
      if (nodeDataBuilder_ == null) {
        return nodeData_ == null ? com.google.devtools.kythe.proto.NodeData.getDefaultInstance() : nodeData_;
      } else {
        return nodeDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public Builder setNodeData(com.google.devtools.kythe.proto.NodeData value) {
      if (nodeDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nodeData_ = value;
        onChanged();
      } else {
        nodeDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public Builder setNodeData(
        com.google.devtools.kythe.proto.NodeData.Builder builderForValue) {
      if (nodeDataBuilder_ == null) {
        nodeData_ = builderForValue.build();
        onChanged();
      } else {
        nodeDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public Builder mergeNodeData(com.google.devtools.kythe.proto.NodeData value) {
      if (nodeDataBuilder_ == null) {
        if (nodeData_ != null) {
          nodeData_ =
            com.google.devtools.kythe.proto.NodeData.newBuilder(nodeData_).mergeFrom(value).buildPartial();
        } else {
          nodeData_ = value;
        }
        onChanged();
      } else {
        nodeDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public Builder clearNodeData() {
      if (nodeDataBuilder_ == null) {
        nodeData_ = null;
        onChanged();
      } else {
        nodeData_ = null;
        nodeDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public com.google.devtools.kythe.proto.NodeData.Builder getNodeDataBuilder() {
      
      onChanged();
      return getNodeDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    public com.google.devtools.kythe.proto.NodeDataOrBuilder getNodeDataOrBuilder() {
      if (nodeDataBuilder_ != null) {
        return nodeDataBuilder_.getMessageOrBuilder();
      } else {
        return nodeData_ == null ?
            com.google.devtools.kythe.proto.NodeData.getDefaultInstance() : nodeData_;
      }
    }
    /**
     * <code>.kythe.proto.NodeData node_data = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.NodeData, com.google.devtools.kythe.proto.NodeData.Builder, com.google.devtools.kythe.proto.NodeDataOrBuilder> 
        getNodeDataFieldBuilder() {
      if (nodeDataBuilder_ == null) {
        nodeDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.kythe.proto.NodeData, com.google.devtools.kythe.proto.NodeData.Builder, com.google.devtools.kythe.proto.NodeDataOrBuilder>(
                getNodeData(),
                getParentForChildren(),
                isClean());
        nodeData_ = null;
      }
      return nodeDataBuilder_;
    }

    private com.google.devtools.kythe.proto.Tickets predecessors_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.Tickets, com.google.devtools.kythe.proto.Tickets.Builder, com.google.devtools.kythe.proto.TicketsOrBuilder> predecessorsBuilder_;
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public boolean hasPredecessors() {
      return predecessorsBuilder_ != null || predecessors_ != null;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public com.google.devtools.kythe.proto.Tickets getPredecessors() {
      if (predecessorsBuilder_ == null) {
        return predecessors_ == null ? com.google.devtools.kythe.proto.Tickets.getDefaultInstance() : predecessors_;
      } else {
        return predecessorsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public Builder setPredecessors(com.google.devtools.kythe.proto.Tickets value) {
      if (predecessorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        predecessors_ = value;
        onChanged();
      } else {
        predecessorsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public Builder setPredecessors(
        com.google.devtools.kythe.proto.Tickets.Builder builderForValue) {
      if (predecessorsBuilder_ == null) {
        predecessors_ = builderForValue.build();
        onChanged();
      } else {
        predecessorsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public Builder mergePredecessors(com.google.devtools.kythe.proto.Tickets value) {
      if (predecessorsBuilder_ == null) {
        if (predecessors_ != null) {
          predecessors_ =
            com.google.devtools.kythe.proto.Tickets.newBuilder(predecessors_).mergeFrom(value).buildPartial();
        } else {
          predecessors_ = value;
        }
        onChanged();
      } else {
        predecessorsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public Builder clearPredecessors() {
      if (predecessorsBuilder_ == null) {
        predecessors_ = null;
        onChanged();
      } else {
        predecessors_ = null;
        predecessorsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public com.google.devtools.kythe.proto.Tickets.Builder getPredecessorsBuilder() {
      
      onChanged();
      return getPredecessorsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    public com.google.devtools.kythe.proto.TicketsOrBuilder getPredecessorsOrBuilder() {
      if (predecessorsBuilder_ != null) {
        return predecessorsBuilder_.getMessageOrBuilder();
      } else {
        return predecessors_ == null ?
            com.google.devtools.kythe.proto.Tickets.getDefaultInstance() : predecessors_;
      }
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by incoming edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets predecessors = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.Tickets, com.google.devtools.kythe.proto.Tickets.Builder, com.google.devtools.kythe.proto.TicketsOrBuilder> 
        getPredecessorsFieldBuilder() {
      if (predecessorsBuilder_ == null) {
        predecessorsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.kythe.proto.Tickets, com.google.devtools.kythe.proto.Tickets.Builder, com.google.devtools.kythe.proto.TicketsOrBuilder>(
                getPredecessors(),
                getParentForChildren(),
                isClean());
        predecessors_ = null;
      }
      return predecessorsBuilder_;
    }

    private com.google.devtools.kythe.proto.Tickets successors_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.Tickets, com.google.devtools.kythe.proto.Tickets.Builder, com.google.devtools.kythe.proto.TicketsOrBuilder> successorsBuilder_;
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public boolean hasSuccessors() {
      return successorsBuilder_ != null || successors_ != null;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public com.google.devtools.kythe.proto.Tickets getSuccessors() {
      if (successorsBuilder_ == null) {
        return successors_ == null ? com.google.devtools.kythe.proto.Tickets.getDefaultInstance() : successors_;
      } else {
        return successorsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public Builder setSuccessors(com.google.devtools.kythe.proto.Tickets value) {
      if (successorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        successors_ = value;
        onChanged();
      } else {
        successorsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public Builder setSuccessors(
        com.google.devtools.kythe.proto.Tickets.Builder builderForValue) {
      if (successorsBuilder_ == null) {
        successors_ = builderForValue.build();
        onChanged();
      } else {
        successorsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public Builder mergeSuccessors(com.google.devtools.kythe.proto.Tickets value) {
      if (successorsBuilder_ == null) {
        if (successors_ != null) {
          successors_ =
            com.google.devtools.kythe.proto.Tickets.newBuilder(successors_).mergeFrom(value).buildPartial();
        } else {
          successors_ = value;
        }
        onChanged();
      } else {
        successorsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public Builder clearSuccessors() {
      if (successorsBuilder_ == null) {
        successors_ = null;
        onChanged();
      } else {
        successors_ = null;
        successorsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public com.google.devtools.kythe.proto.Tickets.Builder getSuccessorsBuilder() {
      
      onChanged();
      return getSuccessorsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    public com.google.devtools.kythe.proto.TicketsOrBuilder getSuccessorsOrBuilder() {
      if (successorsBuilder_ != null) {
        return successorsBuilder_.getMessageOrBuilder();
      } else {
        return successors_ == null ?
            com.google.devtools.kythe.proto.Tickets.getDefaultInstance() : successors_;
      }
    }
    /**
     * <pre>
     * semantic tickets of nodes connected to this node by outgoing edges
     * </pre>
     *
     * <code>.kythe.proto.Tickets successors = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.Tickets, com.google.devtools.kythe.proto.Tickets.Builder, com.google.devtools.kythe.proto.TicketsOrBuilder> 
        getSuccessorsFieldBuilder() {
      if (successorsBuilder_ == null) {
        successorsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.kythe.proto.Tickets, com.google.devtools.kythe.proto.Tickets.Builder, com.google.devtools.kythe.proto.TicketsOrBuilder>(
                getSuccessors(),
                getParentForChildren(),
                isClean());
        successors_ = null;
      }
      return successorsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kythe.proto.GraphNode)
  }

  // @@protoc_insertion_point(class_scope:kythe.proto.GraphNode)
  private static final com.google.devtools.kythe.proto.GraphNode DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.kythe.proto.GraphNode();
  }

  public static com.google.devtools.kythe.proto.GraphNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GraphNode>
      PARSER = new com.google.protobuf.AbstractParser<GraphNode>() {
    public GraphNode parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GraphNode(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GraphNode> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GraphNode> getParserForType() {
    return PARSER;
  }

  public com.google.devtools.kythe.proto.GraphNode getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

