// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/explore.proto

package com.google.devtools.kythe.proto;

public interface GraphNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kythe.proto.GraphNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kythe.proto.NodeData node_data = 1;</code>
   */
  boolean hasNodeData();
  /**
   * <code>.kythe.proto.NodeData node_data = 1;</code>
   */
  com.google.devtools.kythe.proto.NodeData getNodeData();
  /**
   * <code>.kythe.proto.NodeData node_data = 1;</code>
   */
  com.google.devtools.kythe.proto.NodeDataOrBuilder getNodeDataOrBuilder();

  /**
   * <pre>
   * semantic tickets of nodes connected to this node by incoming edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets predecessors = 2;</code>
   */
  boolean hasPredecessors();
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by incoming edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets predecessors = 2;</code>
   */
  com.google.devtools.kythe.proto.Tickets getPredecessors();
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by incoming edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets predecessors = 2;</code>
   */
  com.google.devtools.kythe.proto.TicketsOrBuilder getPredecessorsOrBuilder();

  /**
   * <pre>
   * semantic tickets of nodes connected to this node by outgoing edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets successors = 3;</code>
   */
  boolean hasSuccessors();
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by outgoing edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets successors = 3;</code>
   */
  com.google.devtools.kythe.proto.Tickets getSuccessors();
  /**
   * <pre>
   * semantic tickets of nodes connected to this node by outgoing edges
   * </pre>
   *
   * <code>.kythe.proto.Tickets successors = 3;</code>
   */
  com.google.devtools.kythe.proto.TicketsOrBuilder getSuccessorsOrBuilder();
}
