// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/common.proto

package com.google.devtools.kythe.proto;

public interface MarkedSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kythe.proto.common.MarkedSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
   */
  int getKindValue();
  /**
   * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
   */
  com.google.devtools.kythe.proto.MarkedSource.Kind getKind();

  /**
   * <pre>
   * Nodes expect to be printed as:
   * pre_text + (child + post_child_text)* + post_text
   * where post_child_text is not included after the final child unless
   * add_final_list_token is asserted. post_child_text should never be
   * printed if there are no children.
   * </pre>
   *
   * <code>string pre_text = 2;</code>
   */
  java.lang.String getPreText();
  /**
   * <pre>
   * Nodes expect to be printed as:
   * pre_text + (child + post_child_text)* + post_text
   * where post_child_text is not included after the final child unless
   * add_final_list_token is asserted. post_child_text should never be
   * printed if there are no children.
   * </pre>
   *
   * <code>string pre_text = 2;</code>
   */
  com.google.protobuf.ByteString
      getPreTextBytes();

  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  java.util.List<com.google.devtools.kythe.proto.MarkedSource> 
      getChildList();
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  com.google.devtools.kythe.proto.MarkedSource getChild(int index);
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  int getChildCount();
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  java.util.List<? extends com.google.devtools.kythe.proto.MarkedSourceOrBuilder> 
      getChildOrBuilderList();
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  com.google.devtools.kythe.proto.MarkedSourceOrBuilder getChildOrBuilder(
      int index);

  /**
   * <code>string post_child_text = 4;</code>
   */
  java.lang.String getPostChildText();
  /**
   * <code>string post_child_text = 4;</code>
   */
  com.google.protobuf.ByteString
      getPostChildTextBytes();

  /**
   * <code>string post_text = 5;</code>
   */
  java.lang.String getPostText();
  /**
   * <code>string post_text = 5;</code>
   */
  com.google.protobuf.ByteString
      getPostTextBytes();

  /**
   * <code>uint32 lookup_index = 6;</code>
   */
  int getLookupIndex();

  /**
   * <pre>
   * The default_children_count children at the end of the child list should
   * be considered as "default" or uninteresting.
   * </pre>
   *
   * <code>uint32 default_children_count = 7;</code>
   */
  int getDefaultChildrenCount();

  /**
   * <pre>
   * `add_final_list_token` ensures that `post_child_text` will be
   * included after any nonempty list when that list is followed by additional
   * text.
   * </pre>
   *
   * <code>bool add_final_list_token = 10;</code>
   */
  boolean getAddFinalListToken();

  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  java.util.List<com.google.devtools.kythe.proto.Link> 
      getLinkList();
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  com.google.devtools.kythe.proto.Link getLink(int index);
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  int getLinkCount();
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  java.util.List<? extends com.google.devtools.kythe.proto.LinkOrBuilder> 
      getLinkOrBuilderList();
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  com.google.devtools.kythe.proto.LinkOrBuilder getLinkOrBuilder(
      int index);
}
