// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/common.proto

package com.google.devtools.kythe.proto;

/**
 * <pre>
 * Marked up, source code-like text.
 * </pre>
 *
 * Protobuf type {@code kythe.proto.common.MarkedSource}
 */
public  final class MarkedSource extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kythe.proto.common.MarkedSource)
    MarkedSourceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MarkedSource.newBuilder() to construct.
  private MarkedSource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MarkedSource() {
    kind_ = 0;
    preText_ = "";
    child_ = java.util.Collections.emptyList();
    postChildText_ = "";
    postText_ = "";
    lookupIndex_ = 0;
    defaultChildrenCount_ = 0;
    addFinalListToken_ = false;
    link_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MarkedSource(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            kind_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            preText_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              child_ = new java.util.ArrayList<com.google.devtools.kythe.proto.MarkedSource>();
              mutable_bitField0_ |= 0x00000004;
            }
            child_.add(
                input.readMessage(com.google.devtools.kythe.proto.MarkedSource.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            postChildText_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            postText_ = s;
            break;
          }
          case 48: {

            lookupIndex_ = input.readUInt32();
            break;
          }
          case 56: {

            defaultChildrenCount_ = input.readUInt32();
            break;
          }
          case 80: {

            addFinalListToken_ = input.readBool();
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              link_ = new java.util.ArrayList<com.google.devtools.kythe.proto.Link>();
              mutable_bitField0_ |= 0x00000100;
            }
            link_.add(
                input.readMessage(com.google.devtools.kythe.proto.Link.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        child_ = java.util.Collections.unmodifiableList(child_);
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        link_ = java.util.Collections.unmodifiableList(link_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_MarkedSource_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_MarkedSource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.kythe.proto.MarkedSource.class, com.google.devtools.kythe.proto.MarkedSource.Builder.class);
  }

  /**
   * Protobuf enum {@code kythe.proto.common.MarkedSource.Kind}
   */
  public enum Kind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * This node only contains other nodes and has no special semantics.
     * </pre>
     *
     * <code>BOX = 0;</code>
     */
    BOX(0),
    /**
     * <pre>
     * This node dominates nodes that should be classified as types.
     * </pre>
     *
     * <code>TYPE = 1;</code>
     */
    TYPE(1),
    /**
     * <pre>
     * This node dominates nodes that should be classified as parameters.
     * </pre>
     *
     * <code>PARAMETER = 2;</code>
     */
    PARAMETER(2),
    /**
     * <pre>
     * This node dominates nodes that should be classified as identifiers.
     * </pre>
     *
     * <code>IDENTIFIER = 3;</code>
     */
    IDENTIFIER(3),
    /**
     * <pre>
     * This node dominates nodes that should be classified as context.
     * </pre>
     *
     * <code>CONTEXT = 4;</code>
     */
    CONTEXT(4),
    /**
     * <pre>
     * This node dominates nodes that should be classified as initializers.
     * </pre>
     *
     * <code>INITIALIZER = 5;</code>
     */
    INITIALIZER(5),
    /**
     * <pre>
     * Substitute this node with a PARAMETER formed from the param edges from
     * the context node starting with `lookup_index`.
     * </pre>
     *
     * <code>PARAMETER_LOOKUP_BY_PARAM = 6;</code>
     */
    PARAMETER_LOOKUP_BY_PARAM(6),
    /**
     * <pre>
     * Substitute this node with the marked source derived from the
     * `lookup_index`th param edge of the context node.
     * </pre>
     *
     * <code>LOOKUP_BY_PARAM = 7;</code>
     */
    LOOKUP_BY_PARAM(7),
    /**
     * <pre>
     * Substitute this node with a PARAMETER formed from the param edges from
     * the context node starting with `lookup_index`. Checks the context
     * node for a `param/default` fact and uses that to set the
     * first_default_child field.
     * </pre>
     *
     * <code>PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS = 8;</code>
     */
    PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * This node only contains other nodes and has no special semantics.
     * </pre>
     *
     * <code>BOX = 0;</code>
     */
    public static final int BOX_VALUE = 0;
    /**
     * <pre>
     * This node dominates nodes that should be classified as types.
     * </pre>
     *
     * <code>TYPE = 1;</code>
     */
    public static final int TYPE_VALUE = 1;
    /**
     * <pre>
     * This node dominates nodes that should be classified as parameters.
     * </pre>
     *
     * <code>PARAMETER = 2;</code>
     */
    public static final int PARAMETER_VALUE = 2;
    /**
     * <pre>
     * This node dominates nodes that should be classified as identifiers.
     * </pre>
     *
     * <code>IDENTIFIER = 3;</code>
     */
    public static final int IDENTIFIER_VALUE = 3;
    /**
     * <pre>
     * This node dominates nodes that should be classified as context.
     * </pre>
     *
     * <code>CONTEXT = 4;</code>
     */
    public static final int CONTEXT_VALUE = 4;
    /**
     * <pre>
     * This node dominates nodes that should be classified as initializers.
     * </pre>
     *
     * <code>INITIALIZER = 5;</code>
     */
    public static final int INITIALIZER_VALUE = 5;
    /**
     * <pre>
     * Substitute this node with a PARAMETER formed from the param edges from
     * the context node starting with `lookup_index`.
     * </pre>
     *
     * <code>PARAMETER_LOOKUP_BY_PARAM = 6;</code>
     */
    public static final int PARAMETER_LOOKUP_BY_PARAM_VALUE = 6;
    /**
     * <pre>
     * Substitute this node with the marked source derived from the
     * `lookup_index`th param edge of the context node.
     * </pre>
     *
     * <code>LOOKUP_BY_PARAM = 7;</code>
     */
    public static final int LOOKUP_BY_PARAM_VALUE = 7;
    /**
     * <pre>
     * Substitute this node with a PARAMETER formed from the param edges from
     * the context node starting with `lookup_index`. Checks the context
     * node for a `param/default` fact and uses that to set the
     * first_default_child field.
     * </pre>
     *
     * <code>PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS = 8;</code>
     */
    public static final int PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Kind valueOf(int value) {
      return forNumber(value);
    }

    public static Kind forNumber(int value) {
      switch (value) {
        case 0: return BOX;
        case 1: return TYPE;
        case 2: return PARAMETER;
        case 3: return IDENTIFIER;
        case 4: return CONTEXT;
        case 5: return INITIALIZER;
        case 6: return PARAMETER_LOOKUP_BY_PARAM;
        case 7: return LOOKUP_BY_PARAM;
        case 8: return PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Kind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Kind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
            public Kind findValueByNumber(int number) {
              return Kind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.MarkedSource.getDescriptor().getEnumTypes().get(0);
    }

    private static final Kind[] VALUES = values();

    public static Kind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Kind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kythe.proto.common.MarkedSource.Kind)
  }

  private int bitField0_;
  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_;
  /**
   * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
   */
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
   */
  public com.google.devtools.kythe.proto.MarkedSource.Kind getKind() {
    com.google.devtools.kythe.proto.MarkedSource.Kind result = com.google.devtools.kythe.proto.MarkedSource.Kind.valueOf(kind_);
    return result == null ? com.google.devtools.kythe.proto.MarkedSource.Kind.UNRECOGNIZED : result;
  }

  public static final int PRE_TEXT_FIELD_NUMBER = 2;
  private volatile java.lang.Object preText_;
  /**
   * <pre>
   * Nodes expect to be printed as:
   * pre_text + (child + post_child_text)* + post_text
   * where post_child_text is not included after the final child unless
   * add_final_list_token is asserted. post_child_text should never be
   * printed if there are no children.
   * </pre>
   *
   * <code>string pre_text = 2;</code>
   */
  public java.lang.String getPreText() {
    java.lang.Object ref = preText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      preText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Nodes expect to be printed as:
   * pre_text + (child + post_child_text)* + post_text
   * where post_child_text is not included after the final child unless
   * add_final_list_token is asserted. post_child_text should never be
   * printed if there are no children.
   * </pre>
   *
   * <code>string pre_text = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPreTextBytes() {
    java.lang.Object ref = preText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILD_FIELD_NUMBER = 3;
  private java.util.List<com.google.devtools.kythe.proto.MarkedSource> child_;
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  public java.util.List<com.google.devtools.kythe.proto.MarkedSource> getChildList() {
    return child_;
  }
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  public java.util.List<? extends com.google.devtools.kythe.proto.MarkedSourceOrBuilder> 
      getChildOrBuilderList() {
    return child_;
  }
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  public int getChildCount() {
    return child_.size();
  }
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  public com.google.devtools.kythe.proto.MarkedSource getChild(int index) {
    return child_.get(index);
  }
  /**
   * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
   */
  public com.google.devtools.kythe.proto.MarkedSourceOrBuilder getChildOrBuilder(
      int index) {
    return child_.get(index);
  }

  public static final int POST_CHILD_TEXT_FIELD_NUMBER = 4;
  private volatile java.lang.Object postChildText_;
  /**
   * <code>string post_child_text = 4;</code>
   */
  public java.lang.String getPostChildText() {
    java.lang.Object ref = postChildText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postChildText_ = s;
      return s;
    }
  }
  /**
   * <code>string post_child_text = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPostChildTextBytes() {
    java.lang.Object ref = postChildText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postChildText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POST_TEXT_FIELD_NUMBER = 5;
  private volatile java.lang.Object postText_;
  /**
   * <code>string post_text = 5;</code>
   */
  public java.lang.String getPostText() {
    java.lang.Object ref = postText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postText_ = s;
      return s;
    }
  }
  /**
   * <code>string post_text = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPostTextBytes() {
    java.lang.Object ref = postText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOOKUP_INDEX_FIELD_NUMBER = 6;
  private int lookupIndex_;
  /**
   * <code>uint32 lookup_index = 6;</code>
   */
  public int getLookupIndex() {
    return lookupIndex_;
  }

  public static final int DEFAULT_CHILDREN_COUNT_FIELD_NUMBER = 7;
  private int defaultChildrenCount_;
  /**
   * <pre>
   * The default_children_count children at the end of the child list should
   * be considered as "default" or uninteresting.
   * </pre>
   *
   * <code>uint32 default_children_count = 7;</code>
   */
  public int getDefaultChildrenCount() {
    return defaultChildrenCount_;
  }

  public static final int ADD_FINAL_LIST_TOKEN_FIELD_NUMBER = 10;
  private boolean addFinalListToken_;
  /**
   * <pre>
   * `add_final_list_token` ensures that `post_child_text` will be
   * included after any nonempty list when that list is followed by additional
   * text.
   * </pre>
   *
   * <code>bool add_final_list_token = 10;</code>
   */
  public boolean getAddFinalListToken() {
    return addFinalListToken_;
  }

  public static final int LINK_FIELD_NUMBER = 11;
  private java.util.List<com.google.devtools.kythe.proto.Link> link_;
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  public java.util.List<com.google.devtools.kythe.proto.Link> getLinkList() {
    return link_;
  }
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  public java.util.List<? extends com.google.devtools.kythe.proto.LinkOrBuilder> 
      getLinkOrBuilderList() {
    return link_;
  }
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  public int getLinkCount() {
    return link_.size();
  }
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  public com.google.devtools.kythe.proto.Link getLink(int index) {
    return link_.get(index);
  }
  /**
   * <pre>
   * Annotations covering this subtree's full span.
   * </pre>
   *
   * <code>repeated .kythe.proto.common.Link link = 11;</code>
   */
  public com.google.devtools.kythe.proto.LinkOrBuilder getLinkOrBuilder(
      int index) {
    return link_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kind_ != com.google.devtools.kythe.proto.MarkedSource.Kind.BOX.getNumber()) {
      output.writeEnum(1, kind_);
    }
    if (!getPreTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, preText_);
    }
    for (int i = 0; i < child_.size(); i++) {
      output.writeMessage(3, child_.get(i));
    }
    if (!getPostChildTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, postChildText_);
    }
    if (!getPostTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, postText_);
    }
    if (lookupIndex_ != 0) {
      output.writeUInt32(6, lookupIndex_);
    }
    if (defaultChildrenCount_ != 0) {
      output.writeUInt32(7, defaultChildrenCount_);
    }
    if (addFinalListToken_ != false) {
      output.writeBool(10, addFinalListToken_);
    }
    for (int i = 0; i < link_.size(); i++) {
      output.writeMessage(11, link_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kind_ != com.google.devtools.kythe.proto.MarkedSource.Kind.BOX.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, kind_);
    }
    if (!getPreTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, preText_);
    }
    for (int i = 0; i < child_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, child_.get(i));
    }
    if (!getPostChildTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, postChildText_);
    }
    if (!getPostTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, postText_);
    }
    if (lookupIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, lookupIndex_);
    }
    if (defaultChildrenCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, defaultChildrenCount_);
    }
    if (addFinalListToken_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, addFinalListToken_);
    }
    for (int i = 0; i < link_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, link_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.kythe.proto.MarkedSource)) {
      return super.equals(obj);
    }
    com.google.devtools.kythe.proto.MarkedSource other = (com.google.devtools.kythe.proto.MarkedSource) obj;

    boolean result = true;
    result = result && kind_ == other.kind_;
    result = result && getPreText()
        .equals(other.getPreText());
    result = result && getChildList()
        .equals(other.getChildList());
    result = result && getPostChildText()
        .equals(other.getPostChildText());
    result = result && getPostText()
        .equals(other.getPostText());
    result = result && (getLookupIndex()
        == other.getLookupIndex());
    result = result && (getDefaultChildrenCount()
        == other.getDefaultChildrenCount());
    result = result && (getAddFinalListToken()
        == other.getAddFinalListToken());
    result = result && getLinkList()
        .equals(other.getLinkList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + kind_;
    hash = (37 * hash) + PRE_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getPreText().hashCode();
    if (getChildCount() > 0) {
      hash = (37 * hash) + CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getChildList().hashCode();
    }
    hash = (37 * hash) + POST_CHILD_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getPostChildText().hashCode();
    hash = (37 * hash) + POST_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getPostText().hashCode();
    hash = (37 * hash) + LOOKUP_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getLookupIndex();
    hash = (37 * hash) + DEFAULT_CHILDREN_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultChildrenCount();
    hash = (37 * hash) + ADD_FINAL_LIST_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAddFinalListToken());
    if (getLinkCount() > 0) {
      hash = (37 * hash) + LINK_FIELD_NUMBER;
      hash = (53 * hash) + getLinkList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.MarkedSource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.kythe.proto.MarkedSource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Marked up, source code-like text.
   * </pre>
   *
   * Protobuf type {@code kythe.proto.common.MarkedSource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kythe.proto.common.MarkedSource)
      com.google.devtools.kythe.proto.MarkedSourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_MarkedSource_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_MarkedSource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.kythe.proto.MarkedSource.class, com.google.devtools.kythe.proto.MarkedSource.Builder.class);
    }

    // Construct using com.google.devtools.kythe.proto.MarkedSource.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChildFieldBuilder();
        getLinkFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      kind_ = 0;

      preText_ = "";

      if (childBuilder_ == null) {
        child_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        childBuilder_.clear();
      }
      postChildText_ = "";

      postText_ = "";

      lookupIndex_ = 0;

      defaultChildrenCount_ = 0;

      addFinalListToken_ = false;

      if (linkBuilder_ == null) {
        link_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        linkBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_MarkedSource_descriptor;
    }

    public com.google.devtools.kythe.proto.MarkedSource getDefaultInstanceForType() {
      return com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance();
    }

    public com.google.devtools.kythe.proto.MarkedSource build() {
      com.google.devtools.kythe.proto.MarkedSource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.devtools.kythe.proto.MarkedSource buildPartial() {
      com.google.devtools.kythe.proto.MarkedSource result = new com.google.devtools.kythe.proto.MarkedSource(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.kind_ = kind_;
      result.preText_ = preText_;
      if (childBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          child_ = java.util.Collections.unmodifiableList(child_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.child_ = child_;
      } else {
        result.child_ = childBuilder_.build();
      }
      result.postChildText_ = postChildText_;
      result.postText_ = postText_;
      result.lookupIndex_ = lookupIndex_;
      result.defaultChildrenCount_ = defaultChildrenCount_;
      result.addFinalListToken_ = addFinalListToken_;
      if (linkBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          link_ = java.util.Collections.unmodifiableList(link_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.link_ = link_;
      } else {
        result.link_ = linkBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.kythe.proto.MarkedSource) {
        return mergeFrom((com.google.devtools.kythe.proto.MarkedSource)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.kythe.proto.MarkedSource other) {
      if (other == com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance()) return this;
      if (other.kind_ != 0) {
        setKindValue(other.getKindValue());
      }
      if (!other.getPreText().isEmpty()) {
        preText_ = other.preText_;
        onChanged();
      }
      if (childBuilder_ == null) {
        if (!other.child_.isEmpty()) {
          if (child_.isEmpty()) {
            child_ = other.child_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureChildIsMutable();
            child_.addAll(other.child_);
          }
          onChanged();
        }
      } else {
        if (!other.child_.isEmpty()) {
          if (childBuilder_.isEmpty()) {
            childBuilder_.dispose();
            childBuilder_ = null;
            child_ = other.child_;
            bitField0_ = (bitField0_ & ~0x00000004);
            childBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildFieldBuilder() : null;
          } else {
            childBuilder_.addAllMessages(other.child_);
          }
        }
      }
      if (!other.getPostChildText().isEmpty()) {
        postChildText_ = other.postChildText_;
        onChanged();
      }
      if (!other.getPostText().isEmpty()) {
        postText_ = other.postText_;
        onChanged();
      }
      if (other.getLookupIndex() != 0) {
        setLookupIndex(other.getLookupIndex());
      }
      if (other.getDefaultChildrenCount() != 0) {
        setDefaultChildrenCount(other.getDefaultChildrenCount());
      }
      if (other.getAddFinalListToken() != false) {
        setAddFinalListToken(other.getAddFinalListToken());
      }
      if (linkBuilder_ == null) {
        if (!other.link_.isEmpty()) {
          if (link_.isEmpty()) {
            link_ = other.link_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureLinkIsMutable();
            link_.addAll(other.link_);
          }
          onChanged();
        }
      } else {
        if (!other.link_.isEmpty()) {
          if (linkBuilder_.isEmpty()) {
            linkBuilder_.dispose();
            linkBuilder_ = null;
            link_ = other.link_;
            bitField0_ = (bitField0_ & ~0x00000100);
            linkBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLinkFieldBuilder() : null;
          } else {
            linkBuilder_.addAllMessages(other.link_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.kythe.proto.MarkedSource parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.kythe.proto.MarkedSource) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int kind_ = 0;
    /**
     * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
     */
    public int getKindValue() {
      return kind_;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
     */
    public Builder setKindValue(int value) {
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource.Kind getKind() {
      com.google.devtools.kythe.proto.MarkedSource.Kind result = com.google.devtools.kythe.proto.MarkedSource.Kind.valueOf(kind_);
      return result == null ? com.google.devtools.kythe.proto.MarkedSource.Kind.UNRECOGNIZED : result;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
     */
    public Builder setKind(com.google.devtools.kythe.proto.MarkedSource.Kind value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource.Kind kind = 1;</code>
     */
    public Builder clearKind() {
      
      kind_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object preText_ = "";
    /**
     * <pre>
     * Nodes expect to be printed as:
     * pre_text + (child + post_child_text)* + post_text
     * where post_child_text is not included after the final child unless
     * add_final_list_token is asserted. post_child_text should never be
     * printed if there are no children.
     * </pre>
     *
     * <code>string pre_text = 2;</code>
     */
    public java.lang.String getPreText() {
      java.lang.Object ref = preText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Nodes expect to be printed as:
     * pre_text + (child + post_child_text)* + post_text
     * where post_child_text is not included after the final child unless
     * add_final_list_token is asserted. post_child_text should never be
     * printed if there are no children.
     * </pre>
     *
     * <code>string pre_text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPreTextBytes() {
      java.lang.Object ref = preText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Nodes expect to be printed as:
     * pre_text + (child + post_child_text)* + post_text
     * where post_child_text is not included after the final child unless
     * add_final_list_token is asserted. post_child_text should never be
     * printed if there are no children.
     * </pre>
     *
     * <code>string pre_text = 2;</code>
     */
    public Builder setPreText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      preText_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Nodes expect to be printed as:
     * pre_text + (child + post_child_text)* + post_text
     * where post_child_text is not included after the final child unless
     * add_final_list_token is asserted. post_child_text should never be
     * printed if there are no children.
     * </pre>
     *
     * <code>string pre_text = 2;</code>
     */
    public Builder clearPreText() {
      
      preText_ = getDefaultInstance().getPreText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Nodes expect to be printed as:
     * pre_text + (child + post_child_text)* + post_text
     * where post_child_text is not included after the final child unless
     * add_final_list_token is asserted. post_child_text should never be
     * printed if there are no children.
     * </pre>
     *
     * <code>string pre_text = 2;</code>
     */
    public Builder setPreTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      preText_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.devtools.kythe.proto.MarkedSource> child_ =
      java.util.Collections.emptyList();
    private void ensureChildIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        child_ = new java.util.ArrayList<com.google.devtools.kythe.proto.MarkedSource>(child_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.kythe.proto.MarkedSource, com.google.devtools.kythe.proto.MarkedSource.Builder, com.google.devtools.kythe.proto.MarkedSourceOrBuilder> childBuilder_;

    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public java.util.List<com.google.devtools.kythe.proto.MarkedSource> getChildList() {
      if (childBuilder_ == null) {
        return java.util.Collections.unmodifiableList(child_);
      } else {
        return childBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public int getChildCount() {
      if (childBuilder_ == null) {
        return child_.size();
      } else {
        return childBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource getChild(int index) {
      if (childBuilder_ == null) {
        return child_.get(index);
      } else {
        return childBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder setChild(
        int index, com.google.devtools.kythe.proto.MarkedSource value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildIsMutable();
        child_.set(index, value);
        onChanged();
      } else {
        childBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder setChild(
        int index, com.google.devtools.kythe.proto.MarkedSource.Builder builderForValue) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.set(index, builderForValue.build());
        onChanged();
      } else {
        childBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder addChild(com.google.devtools.kythe.proto.MarkedSource value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildIsMutable();
        child_.add(value);
        onChanged();
      } else {
        childBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder addChild(
        int index, com.google.devtools.kythe.proto.MarkedSource value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildIsMutable();
        child_.add(index, value);
        onChanged();
      } else {
        childBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder addChild(
        com.google.devtools.kythe.proto.MarkedSource.Builder builderForValue) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.add(builderForValue.build());
        onChanged();
      } else {
        childBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder addChild(
        int index, com.google.devtools.kythe.proto.MarkedSource.Builder builderForValue) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.add(index, builderForValue.build());
        onChanged();
      } else {
        childBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder addAllChild(
        java.lang.Iterable<? extends com.google.devtools.kythe.proto.MarkedSource> values) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, child_);
        onChanged();
      } else {
        childBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder clearChild() {
      if (childBuilder_ == null) {
        child_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        childBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public Builder removeChild(int index) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.remove(index);
        onChanged();
      } else {
        childBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource.Builder getChildBuilder(
        int index) {
      return getChildFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSourceOrBuilder getChildOrBuilder(
        int index) {
      if (childBuilder_ == null) {
        return child_.get(index);  } else {
        return childBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public java.util.List<? extends com.google.devtools.kythe.proto.MarkedSourceOrBuilder> 
         getChildOrBuilderList() {
      if (childBuilder_ != null) {
        return childBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(child_);
      }
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource.Builder addChildBuilder() {
      return getChildFieldBuilder().addBuilder(
          com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance());
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource.Builder addChildBuilder(
        int index) {
      return getChildFieldBuilder().addBuilder(
          index, com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance());
    }
    /**
     * <code>repeated .kythe.proto.common.MarkedSource child = 3;</code>
     */
    public java.util.List<com.google.devtools.kythe.proto.MarkedSource.Builder> 
         getChildBuilderList() {
      return getChildFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.kythe.proto.MarkedSource, com.google.devtools.kythe.proto.MarkedSource.Builder, com.google.devtools.kythe.proto.MarkedSourceOrBuilder> 
        getChildFieldBuilder() {
      if (childBuilder_ == null) {
        childBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.devtools.kythe.proto.MarkedSource, com.google.devtools.kythe.proto.MarkedSource.Builder, com.google.devtools.kythe.proto.MarkedSourceOrBuilder>(
                child_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        child_ = null;
      }
      return childBuilder_;
    }

    private java.lang.Object postChildText_ = "";
    /**
     * <code>string post_child_text = 4;</code>
     */
    public java.lang.String getPostChildText() {
      java.lang.Object ref = postChildText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postChildText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string post_child_text = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPostChildTextBytes() {
      java.lang.Object ref = postChildText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postChildText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string post_child_text = 4;</code>
     */
    public Builder setPostChildText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postChildText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string post_child_text = 4;</code>
     */
    public Builder clearPostChildText() {
      
      postChildText_ = getDefaultInstance().getPostChildText();
      onChanged();
      return this;
    }
    /**
     * <code>string post_child_text = 4;</code>
     */
    public Builder setPostChildTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postChildText_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object postText_ = "";
    /**
     * <code>string post_text = 5;</code>
     */
    public java.lang.String getPostText() {
      java.lang.Object ref = postText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string post_text = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPostTextBytes() {
      java.lang.Object ref = postText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string post_text = 5;</code>
     */
    public Builder setPostText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string post_text = 5;</code>
     */
    public Builder clearPostText() {
      
      postText_ = getDefaultInstance().getPostText();
      onChanged();
      return this;
    }
    /**
     * <code>string post_text = 5;</code>
     */
    public Builder setPostTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postText_ = value;
      onChanged();
      return this;
    }

    private int lookupIndex_ ;
    /**
     * <code>uint32 lookup_index = 6;</code>
     */
    public int getLookupIndex() {
      return lookupIndex_;
    }
    /**
     * <code>uint32 lookup_index = 6;</code>
     */
    public Builder setLookupIndex(int value) {
      
      lookupIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 lookup_index = 6;</code>
     */
    public Builder clearLookupIndex() {
      
      lookupIndex_ = 0;
      onChanged();
      return this;
    }

    private int defaultChildrenCount_ ;
    /**
     * <pre>
     * The default_children_count children at the end of the child list should
     * be considered as "default" or uninteresting.
     * </pre>
     *
     * <code>uint32 default_children_count = 7;</code>
     */
    public int getDefaultChildrenCount() {
      return defaultChildrenCount_;
    }
    /**
     * <pre>
     * The default_children_count children at the end of the child list should
     * be considered as "default" or uninteresting.
     * </pre>
     *
     * <code>uint32 default_children_count = 7;</code>
     */
    public Builder setDefaultChildrenCount(int value) {
      
      defaultChildrenCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The default_children_count children at the end of the child list should
     * be considered as "default" or uninteresting.
     * </pre>
     *
     * <code>uint32 default_children_count = 7;</code>
     */
    public Builder clearDefaultChildrenCount() {
      
      defaultChildrenCount_ = 0;
      onChanged();
      return this;
    }

    private boolean addFinalListToken_ ;
    /**
     * <pre>
     * `add_final_list_token` ensures that `post_child_text` will be
     * included after any nonempty list when that list is followed by additional
     * text.
     * </pre>
     *
     * <code>bool add_final_list_token = 10;</code>
     */
    public boolean getAddFinalListToken() {
      return addFinalListToken_;
    }
    /**
     * <pre>
     * `add_final_list_token` ensures that `post_child_text` will be
     * included after any nonempty list when that list is followed by additional
     * text.
     * </pre>
     *
     * <code>bool add_final_list_token = 10;</code>
     */
    public Builder setAddFinalListToken(boolean value) {
      
      addFinalListToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * `add_final_list_token` ensures that `post_child_text` will be
     * included after any nonempty list when that list is followed by additional
     * text.
     * </pre>
     *
     * <code>bool add_final_list_token = 10;</code>
     */
    public Builder clearAddFinalListToken() {
      
      addFinalListToken_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.devtools.kythe.proto.Link> link_ =
      java.util.Collections.emptyList();
    private void ensureLinkIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        link_ = new java.util.ArrayList<com.google.devtools.kythe.proto.Link>(link_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.kythe.proto.Link, com.google.devtools.kythe.proto.Link.Builder, com.google.devtools.kythe.proto.LinkOrBuilder> linkBuilder_;

    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public java.util.List<com.google.devtools.kythe.proto.Link> getLinkList() {
      if (linkBuilder_ == null) {
        return java.util.Collections.unmodifiableList(link_);
      } else {
        return linkBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public int getLinkCount() {
      if (linkBuilder_ == null) {
        return link_.size();
      } else {
        return linkBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public com.google.devtools.kythe.proto.Link getLink(int index) {
      if (linkBuilder_ == null) {
        return link_.get(index);
      } else {
        return linkBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder setLink(
        int index, com.google.devtools.kythe.proto.Link value) {
      if (linkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinkIsMutable();
        link_.set(index, value);
        onChanged();
      } else {
        linkBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder setLink(
        int index, com.google.devtools.kythe.proto.Link.Builder builderForValue) {
      if (linkBuilder_ == null) {
        ensureLinkIsMutable();
        link_.set(index, builderForValue.build());
        onChanged();
      } else {
        linkBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder addLink(com.google.devtools.kythe.proto.Link value) {
      if (linkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinkIsMutable();
        link_.add(value);
        onChanged();
      } else {
        linkBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder addLink(
        int index, com.google.devtools.kythe.proto.Link value) {
      if (linkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinkIsMutable();
        link_.add(index, value);
        onChanged();
      } else {
        linkBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder addLink(
        com.google.devtools.kythe.proto.Link.Builder builderForValue) {
      if (linkBuilder_ == null) {
        ensureLinkIsMutable();
        link_.add(builderForValue.build());
        onChanged();
      } else {
        linkBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder addLink(
        int index, com.google.devtools.kythe.proto.Link.Builder builderForValue) {
      if (linkBuilder_ == null) {
        ensureLinkIsMutable();
        link_.add(index, builderForValue.build());
        onChanged();
      } else {
        linkBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder addAllLink(
        java.lang.Iterable<? extends com.google.devtools.kythe.proto.Link> values) {
      if (linkBuilder_ == null) {
        ensureLinkIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, link_);
        onChanged();
      } else {
        linkBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder clearLink() {
      if (linkBuilder_ == null) {
        link_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        linkBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public Builder removeLink(int index) {
      if (linkBuilder_ == null) {
        ensureLinkIsMutable();
        link_.remove(index);
        onChanged();
      } else {
        linkBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public com.google.devtools.kythe.proto.Link.Builder getLinkBuilder(
        int index) {
      return getLinkFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public com.google.devtools.kythe.proto.LinkOrBuilder getLinkOrBuilder(
        int index) {
      if (linkBuilder_ == null) {
        return link_.get(index);  } else {
        return linkBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public java.util.List<? extends com.google.devtools.kythe.proto.LinkOrBuilder> 
         getLinkOrBuilderList() {
      if (linkBuilder_ != null) {
        return linkBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(link_);
      }
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public com.google.devtools.kythe.proto.Link.Builder addLinkBuilder() {
      return getLinkFieldBuilder().addBuilder(
          com.google.devtools.kythe.proto.Link.getDefaultInstance());
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public com.google.devtools.kythe.proto.Link.Builder addLinkBuilder(
        int index) {
      return getLinkFieldBuilder().addBuilder(
          index, com.google.devtools.kythe.proto.Link.getDefaultInstance());
    }
    /**
     * <pre>
     * Annotations covering this subtree's full span.
     * </pre>
     *
     * <code>repeated .kythe.proto.common.Link link = 11;</code>
     */
    public java.util.List<com.google.devtools.kythe.proto.Link.Builder> 
         getLinkBuilderList() {
      return getLinkFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.kythe.proto.Link, com.google.devtools.kythe.proto.Link.Builder, com.google.devtools.kythe.proto.LinkOrBuilder> 
        getLinkFieldBuilder() {
      if (linkBuilder_ == null) {
        linkBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.devtools.kythe.proto.Link, com.google.devtools.kythe.proto.Link.Builder, com.google.devtools.kythe.proto.LinkOrBuilder>(
                link_,
                ((bitField0_ & 0x00000100) == 0x00000100),
                getParentForChildren(),
                isClean());
        link_ = null;
      }
      return linkBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kythe.proto.common.MarkedSource)
  }

  // @@protoc_insertion_point(class_scope:kythe.proto.common.MarkedSource)
  private static final com.google.devtools.kythe.proto.MarkedSource DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.kythe.proto.MarkedSource();
  }

  public static com.google.devtools.kythe.proto.MarkedSource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MarkedSource>
      PARSER = new com.google.protobuf.AbstractParser<MarkedSource>() {
    public MarkedSource parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MarkedSource(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MarkedSource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarkedSource> getParserForType() {
    return PARSER;
  }

  public com.google.devtools.kythe.proto.MarkedSource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

