// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/explore.proto

package com.google.devtools.kythe.proto;

/**
 * Protobuf type {@code kythe.proto.NodeData}
 */
public  final class NodeData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kythe.proto.NodeData)
    NodeDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeData.newBuilder() to construct.
  private NodeData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeData() {
    kind_ = "";
    subkind_ = "";
    locations_ = java.util.Collections.emptyList();
    definitionAnchor_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NodeData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            kind_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            subkind_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              locations_ = new java.util.ArrayList<com.google.devtools.kythe.proto.Location>();
              mutable_bitField0_ |= 0x00000004;
            }
            locations_.add(
                input.readMessage(com.google.devtools.kythe.proto.Location.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            definitionAnchor_ = s;
            break;
          }
          case 42: {
            com.google.devtools.kythe.proto.MarkedSource.Builder subBuilder = null;
            if (code_ != null) {
              subBuilder = code_.toBuilder();
            }
            code_ = input.readMessage(com.google.devtools.kythe.proto.MarkedSource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(code_);
              code_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        locations_ = java.util.Collections.unmodifiableList(locations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_NodeData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_NodeData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.kythe.proto.NodeData.class, com.google.devtools.kythe.proto.NodeData.Builder.class);
  }

  private int bitField0_;
  public static final int KIND_FIELD_NUMBER = 1;
  private volatile java.lang.Object kind_;
  /**
   * <pre>
   * the "node/[sub]kind" node facts
   * </pre>
   *
   * <code>string kind = 1;</code>
   */
  public java.lang.String getKind() {
    java.lang.Object ref = kind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kind_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the "node/[sub]kind" node facts
   * </pre>
   *
   * <code>string kind = 1;</code>
   */
  public com.google.protobuf.ByteString
      getKindBytes() {
    java.lang.Object ref = kind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBKIND_FIELD_NUMBER = 2;
  private volatile java.lang.Object subkind_;
  /**
   * <code>string subkind = 2;</code>
   */
  public java.lang.String getSubkind() {
    java.lang.Object ref = subkind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subkind_ = s;
      return s;
    }
  }
  /**
   * <code>string subkind = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSubkindBytes() {
    java.lang.Object ref = subkind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subkind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATIONS_FIELD_NUMBER = 3;
  private java.util.List<com.google.devtools.kythe.proto.Location> locations_;
  /**
   * <pre>
   * the relevant locations in which this node is found
   * TODO: do we want span-specific locations?
   * </pre>
   *
   * <code>repeated .kythe.proto.Location locations = 3;</code>
   */
  public java.util.List<com.google.devtools.kythe.proto.Location> getLocationsList() {
    return locations_;
  }
  /**
   * <pre>
   * the relevant locations in which this node is found
   * TODO: do we want span-specific locations?
   * </pre>
   *
   * <code>repeated .kythe.proto.Location locations = 3;</code>
   */
  public java.util.List<? extends com.google.devtools.kythe.proto.LocationOrBuilder> 
      getLocationsOrBuilderList() {
    return locations_;
  }
  /**
   * <pre>
   * the relevant locations in which this node is found
   * TODO: do we want span-specific locations?
   * </pre>
   *
   * <code>repeated .kythe.proto.Location locations = 3;</code>
   */
  public int getLocationsCount() {
    return locations_.size();
  }
  /**
   * <pre>
   * the relevant locations in which this node is found
   * TODO: do we want span-specific locations?
   * </pre>
   *
   * <code>repeated .kythe.proto.Location locations = 3;</code>
   */
  public com.google.devtools.kythe.proto.Location getLocations(int index) {
    return locations_.get(index);
  }
  /**
   * <pre>
   * the relevant locations in which this node is found
   * TODO: do we want span-specific locations?
   * </pre>
   *
   * <code>repeated .kythe.proto.Location locations = 3;</code>
   */
  public com.google.devtools.kythe.proto.LocationOrBuilder getLocationsOrBuilder(
      int index) {
    return locations_.get(index);
  }

  public static final int DEFINITION_ANCHOR_FIELD_NUMBER = 4;
  private volatile java.lang.Object definitionAnchor_;
  /**
   * <pre>
   * anchor ticket
   * </pre>
   *
   * <code>string definition_anchor = 4;</code>
   */
  public java.lang.String getDefinitionAnchor() {
    java.lang.Object ref = definitionAnchor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      definitionAnchor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * anchor ticket
   * </pre>
   *
   * <code>string definition_anchor = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDefinitionAnchorBytes() {
    java.lang.Object ref = definitionAnchor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      definitionAnchor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 5;
  private com.google.devtools.kythe.proto.MarkedSource code_;
  /**
   * <code>.kythe.proto.common.MarkedSource code = 5;</code>
   */
  public boolean hasCode() {
    return code_ != null;
  }
  /**
   * <code>.kythe.proto.common.MarkedSource code = 5;</code>
   */
  public com.google.devtools.kythe.proto.MarkedSource getCode() {
    return code_ == null ? com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance() : code_;
  }
  /**
   * <code>.kythe.proto.common.MarkedSource code = 5;</code>
   */
  public com.google.devtools.kythe.proto.MarkedSourceOrBuilder getCodeOrBuilder() {
    return getCode();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKindBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, kind_);
    }
    if (!getSubkindBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subkind_);
    }
    for (int i = 0; i < locations_.size(); i++) {
      output.writeMessage(3, locations_.get(i));
    }
    if (!getDefinitionAnchorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, definitionAnchor_);
    }
    if (code_ != null) {
      output.writeMessage(5, getCode());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKindBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, kind_);
    }
    if (!getSubkindBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subkind_);
    }
    for (int i = 0; i < locations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, locations_.get(i));
    }
    if (!getDefinitionAnchorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, definitionAnchor_);
    }
    if (code_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCode());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.kythe.proto.NodeData)) {
      return super.equals(obj);
    }
    com.google.devtools.kythe.proto.NodeData other = (com.google.devtools.kythe.proto.NodeData) obj;

    boolean result = true;
    result = result && getKind()
        .equals(other.getKind());
    result = result && getSubkind()
        .equals(other.getSubkind());
    result = result && getLocationsList()
        .equals(other.getLocationsList());
    result = result && getDefinitionAnchor()
        .equals(other.getDefinitionAnchor());
    result = result && (hasCode() == other.hasCode());
    if (hasCode()) {
      result = result && getCode()
          .equals(other.getCode());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + getKind().hashCode();
    hash = (37 * hash) + SUBKIND_FIELD_NUMBER;
    hash = (53 * hash) + getSubkind().hashCode();
    if (getLocationsCount() > 0) {
      hash = (37 * hash) + LOCATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getLocationsList().hashCode();
    }
    hash = (37 * hash) + DEFINITION_ANCHOR_FIELD_NUMBER;
    hash = (53 * hash) + getDefinitionAnchor().hashCode();
    if (hasCode()) {
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.NodeData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.NodeData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.NodeData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.kythe.proto.NodeData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kythe.proto.NodeData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kythe.proto.NodeData)
      com.google.devtools.kythe.proto.NodeDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_NodeData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_NodeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.kythe.proto.NodeData.class, com.google.devtools.kythe.proto.NodeData.Builder.class);
    }

    // Construct using com.google.devtools.kythe.proto.NodeData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLocationsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      kind_ = "";

      subkind_ = "";

      if (locationsBuilder_ == null) {
        locations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        locationsBuilder_.clear();
      }
      definitionAnchor_ = "";

      if (codeBuilder_ == null) {
        code_ = null;
      } else {
        code_ = null;
        codeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.kythe.proto.Explore.internal_static_kythe_proto_NodeData_descriptor;
    }

    public com.google.devtools.kythe.proto.NodeData getDefaultInstanceForType() {
      return com.google.devtools.kythe.proto.NodeData.getDefaultInstance();
    }

    public com.google.devtools.kythe.proto.NodeData build() {
      com.google.devtools.kythe.proto.NodeData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.devtools.kythe.proto.NodeData buildPartial() {
      com.google.devtools.kythe.proto.NodeData result = new com.google.devtools.kythe.proto.NodeData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.kind_ = kind_;
      result.subkind_ = subkind_;
      if (locationsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          locations_ = java.util.Collections.unmodifiableList(locations_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.locations_ = locations_;
      } else {
        result.locations_ = locationsBuilder_.build();
      }
      result.definitionAnchor_ = definitionAnchor_;
      if (codeBuilder_ == null) {
        result.code_ = code_;
      } else {
        result.code_ = codeBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.kythe.proto.NodeData) {
        return mergeFrom((com.google.devtools.kythe.proto.NodeData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.kythe.proto.NodeData other) {
      if (other == com.google.devtools.kythe.proto.NodeData.getDefaultInstance()) return this;
      if (!other.getKind().isEmpty()) {
        kind_ = other.kind_;
        onChanged();
      }
      if (!other.getSubkind().isEmpty()) {
        subkind_ = other.subkind_;
        onChanged();
      }
      if (locationsBuilder_ == null) {
        if (!other.locations_.isEmpty()) {
          if (locations_.isEmpty()) {
            locations_ = other.locations_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLocationsIsMutable();
            locations_.addAll(other.locations_);
          }
          onChanged();
        }
      } else {
        if (!other.locations_.isEmpty()) {
          if (locationsBuilder_.isEmpty()) {
            locationsBuilder_.dispose();
            locationsBuilder_ = null;
            locations_ = other.locations_;
            bitField0_ = (bitField0_ & ~0x00000004);
            locationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLocationsFieldBuilder() : null;
          } else {
            locationsBuilder_.addAllMessages(other.locations_);
          }
        }
      }
      if (!other.getDefinitionAnchor().isEmpty()) {
        definitionAnchor_ = other.definitionAnchor_;
        onChanged();
      }
      if (other.hasCode()) {
        mergeCode(other.getCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.kythe.proto.NodeData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.kythe.proto.NodeData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object kind_ = "";
    /**
     * <pre>
     * the "node/[sub]kind" node facts
     * </pre>
     *
     * <code>string kind = 1;</code>
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the "node/[sub]kind" node facts
     * </pre>
     *
     * <code>string kind = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the "node/[sub]kind" node facts
     * </pre>
     *
     * <code>string kind = 1;</code>
     */
    public Builder setKind(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the "node/[sub]kind" node facts
     * </pre>
     *
     * <code>string kind = 1;</code>
     */
    public Builder clearKind() {
      
      kind_ = getDefaultInstance().getKind();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the "node/[sub]kind" node facts
     * </pre>
     *
     * <code>string kind = 1;</code>
     */
    public Builder setKindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      kind_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subkind_ = "";
    /**
     * <code>string subkind = 2;</code>
     */
    public java.lang.String getSubkind() {
      java.lang.Object ref = subkind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subkind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subkind = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubkindBytes() {
      java.lang.Object ref = subkind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subkind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subkind = 2;</code>
     */
    public Builder setSubkind(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subkind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subkind = 2;</code>
     */
    public Builder clearSubkind() {
      
      subkind_ = getDefaultInstance().getSubkind();
      onChanged();
      return this;
    }
    /**
     * <code>string subkind = 2;</code>
     */
    public Builder setSubkindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subkind_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.devtools.kythe.proto.Location> locations_ =
      java.util.Collections.emptyList();
    private void ensureLocationsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        locations_ = new java.util.ArrayList<com.google.devtools.kythe.proto.Location>(locations_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.kythe.proto.Location, com.google.devtools.kythe.proto.Location.Builder, com.google.devtools.kythe.proto.LocationOrBuilder> locationsBuilder_;

    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public java.util.List<com.google.devtools.kythe.proto.Location> getLocationsList() {
      if (locationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(locations_);
      } else {
        return locationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public int getLocationsCount() {
      if (locationsBuilder_ == null) {
        return locations_.size();
      } else {
        return locationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public com.google.devtools.kythe.proto.Location getLocations(int index) {
      if (locationsBuilder_ == null) {
        return locations_.get(index);
      } else {
        return locationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder setLocations(
        int index, com.google.devtools.kythe.proto.Location value) {
      if (locationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationsIsMutable();
        locations_.set(index, value);
        onChanged();
      } else {
        locationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder setLocations(
        int index, com.google.devtools.kythe.proto.Location.Builder builderForValue) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.set(index, builderForValue.build());
        onChanged();
      } else {
        locationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder addLocations(com.google.devtools.kythe.proto.Location value) {
      if (locationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationsIsMutable();
        locations_.add(value);
        onChanged();
      } else {
        locationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder addLocations(
        int index, com.google.devtools.kythe.proto.Location value) {
      if (locationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationsIsMutable();
        locations_.add(index, value);
        onChanged();
      } else {
        locationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder addLocations(
        com.google.devtools.kythe.proto.Location.Builder builderForValue) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.add(builderForValue.build());
        onChanged();
      } else {
        locationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder addLocations(
        int index, com.google.devtools.kythe.proto.Location.Builder builderForValue) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.add(index, builderForValue.build());
        onChanged();
      } else {
        locationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder addAllLocations(
        java.lang.Iterable<? extends com.google.devtools.kythe.proto.Location> values) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, locations_);
        onChanged();
      } else {
        locationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder clearLocations() {
      if (locationsBuilder_ == null) {
        locations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        locationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public Builder removeLocations(int index) {
      if (locationsBuilder_ == null) {
        ensureLocationsIsMutable();
        locations_.remove(index);
        onChanged();
      } else {
        locationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public com.google.devtools.kythe.proto.Location.Builder getLocationsBuilder(
        int index) {
      return getLocationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public com.google.devtools.kythe.proto.LocationOrBuilder getLocationsOrBuilder(
        int index) {
      if (locationsBuilder_ == null) {
        return locations_.get(index);  } else {
        return locationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public java.util.List<? extends com.google.devtools.kythe.proto.LocationOrBuilder> 
         getLocationsOrBuilderList() {
      if (locationsBuilder_ != null) {
        return locationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(locations_);
      }
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public com.google.devtools.kythe.proto.Location.Builder addLocationsBuilder() {
      return getLocationsFieldBuilder().addBuilder(
          com.google.devtools.kythe.proto.Location.getDefaultInstance());
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public com.google.devtools.kythe.proto.Location.Builder addLocationsBuilder(
        int index) {
      return getLocationsFieldBuilder().addBuilder(
          index, com.google.devtools.kythe.proto.Location.getDefaultInstance());
    }
    /**
     * <pre>
     * the relevant locations in which this node is found
     * TODO: do we want span-specific locations?
     * </pre>
     *
     * <code>repeated .kythe.proto.Location locations = 3;</code>
     */
    public java.util.List<com.google.devtools.kythe.proto.Location.Builder> 
         getLocationsBuilderList() {
      return getLocationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.kythe.proto.Location, com.google.devtools.kythe.proto.Location.Builder, com.google.devtools.kythe.proto.LocationOrBuilder> 
        getLocationsFieldBuilder() {
      if (locationsBuilder_ == null) {
        locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.devtools.kythe.proto.Location, com.google.devtools.kythe.proto.Location.Builder, com.google.devtools.kythe.proto.LocationOrBuilder>(
                locations_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        locations_ = null;
      }
      return locationsBuilder_;
    }

    private java.lang.Object definitionAnchor_ = "";
    /**
     * <pre>
     * anchor ticket
     * </pre>
     *
     * <code>string definition_anchor = 4;</code>
     */
    public java.lang.String getDefinitionAnchor() {
      java.lang.Object ref = definitionAnchor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        definitionAnchor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * anchor ticket
     * </pre>
     *
     * <code>string definition_anchor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDefinitionAnchorBytes() {
      java.lang.Object ref = definitionAnchor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        definitionAnchor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * anchor ticket
     * </pre>
     *
     * <code>string definition_anchor = 4;</code>
     */
    public Builder setDefinitionAnchor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      definitionAnchor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * anchor ticket
     * </pre>
     *
     * <code>string definition_anchor = 4;</code>
     */
    public Builder clearDefinitionAnchor() {
      
      definitionAnchor_ = getDefaultInstance().getDefinitionAnchor();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * anchor ticket
     * </pre>
     *
     * <code>string definition_anchor = 4;</code>
     */
    public Builder setDefinitionAnchorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      definitionAnchor_ = value;
      onChanged();
      return this;
    }

    private com.google.devtools.kythe.proto.MarkedSource code_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.MarkedSource, com.google.devtools.kythe.proto.MarkedSource.Builder, com.google.devtools.kythe.proto.MarkedSourceOrBuilder> codeBuilder_;
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public boolean hasCode() {
      return codeBuilder_ != null || code_ != null;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource getCode() {
      if (codeBuilder_ == null) {
        return code_ == null ? com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance() : code_;
      } else {
        return codeBuilder_.getMessage();
      }
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public Builder setCode(com.google.devtools.kythe.proto.MarkedSource value) {
      if (codeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        code_ = value;
        onChanged();
      } else {
        codeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public Builder setCode(
        com.google.devtools.kythe.proto.MarkedSource.Builder builderForValue) {
      if (codeBuilder_ == null) {
        code_ = builderForValue.build();
        onChanged();
      } else {
        codeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public Builder mergeCode(com.google.devtools.kythe.proto.MarkedSource value) {
      if (codeBuilder_ == null) {
        if (code_ != null) {
          code_ =
            com.google.devtools.kythe.proto.MarkedSource.newBuilder(code_).mergeFrom(value).buildPartial();
        } else {
          code_ = value;
        }
        onChanged();
      } else {
        codeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public Builder clearCode() {
      if (codeBuilder_ == null) {
        code_ = null;
        onChanged();
      } else {
        code_ = null;
        codeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSource.Builder getCodeBuilder() {
      
      onChanged();
      return getCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    public com.google.devtools.kythe.proto.MarkedSourceOrBuilder getCodeOrBuilder() {
      if (codeBuilder_ != null) {
        return codeBuilder_.getMessageOrBuilder();
      } else {
        return code_ == null ?
            com.google.devtools.kythe.proto.MarkedSource.getDefaultInstance() : code_;
      }
    }
    /**
     * <code>.kythe.proto.common.MarkedSource code = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.kythe.proto.MarkedSource, com.google.devtools.kythe.proto.MarkedSource.Builder, com.google.devtools.kythe.proto.MarkedSourceOrBuilder> 
        getCodeFieldBuilder() {
      if (codeBuilder_ == null) {
        codeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.kythe.proto.MarkedSource, com.google.devtools.kythe.proto.MarkedSource.Builder, com.google.devtools.kythe.proto.MarkedSourceOrBuilder>(
                getCode(),
                getParentForChildren(),
                isClean());
        code_ = null;
      }
      return codeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kythe.proto.NodeData)
  }

  // @@protoc_insertion_point(class_scope:kythe.proto.NodeData)
  private static final com.google.devtools.kythe.proto.NodeData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.kythe.proto.NodeData();
  }

  public static com.google.devtools.kythe.proto.NodeData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeData>
      PARSER = new com.google.protobuf.AbstractParser<NodeData>() {
    public NodeData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NodeData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NodeData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeData> getParserForType() {
    return PARSER;
  }

  public com.google.devtools.kythe.proto.NodeData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

