// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/explore.proto

package com.google.devtools.kythe.proto;

public interface ParentsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kythe.proto.ParentsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string ticket = 1;</code>
   */
  java.util.List<java.lang.String>
      getTicketList();
  /**
   * <code>repeated string ticket = 1;</code>
   */
  int getTicketCount();
  /**
   * <code>repeated string ticket = 1;</code>
   */
  java.lang.String getTicket(int index);
  /**
   * <code>repeated string ticket = 1;</code>
   */
  com.google.protobuf.ByteString
      getTicketBytes(int index);
}
