// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kythe/proto/common.proto

package com.google.devtools.kythe.proto;

/**
 * <pre>
 * Contains symbol information for Kythe graph nodes.
 * </pre>
 *
 * Protobuf type {@code kythe.proto.common.SymbolInfo}
 */
public  final class SymbolInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kythe.proto.common.SymbolInfo)
    SymbolInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SymbolInfo.newBuilder() to construct.
  private SymbolInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SymbolInfo() {
    baseName_ = "";
    qualifiedName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SymbolInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            baseName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            qualifiedName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_SymbolInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_SymbolInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.kythe.proto.SymbolInfo.class, com.google.devtools.kythe.proto.SymbolInfo.Builder.class);
  }

  public static final int BASE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object baseName_;
  /**
   * <pre>
   * The base un-qualified name for a node.
   * </pre>
   *
   * <code>string base_name = 1;</code>
   */
  public java.lang.String getBaseName() {
    java.lang.Object ref = baseName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The base un-qualified name for a node.
   * </pre>
   *
   * <code>string base_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBaseNameBytes() {
    java.lang.Object ref = baseName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUALIFIED_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object qualifiedName_;
  /**
   * <pre>
   * The fully qualified name for a node.
   * </pre>
   *
   * <code>string qualified_name = 2;</code>
   */
  public java.lang.String getQualifiedName() {
    java.lang.Object ref = qualifiedName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      qualifiedName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The fully qualified name for a node.
   * </pre>
   *
   * <code>string qualified_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getQualifiedNameBytes() {
    java.lang.Object ref = qualifiedName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      qualifiedName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBaseNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, baseName_);
    }
    if (!getQualifiedNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, qualifiedName_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBaseNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, baseName_);
    }
    if (!getQualifiedNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, qualifiedName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.kythe.proto.SymbolInfo)) {
      return super.equals(obj);
    }
    com.google.devtools.kythe.proto.SymbolInfo other = (com.google.devtools.kythe.proto.SymbolInfo) obj;

    boolean result = true;
    result = result && getBaseName()
        .equals(other.getBaseName());
    result = result && getQualifiedName()
        .equals(other.getQualifiedName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BASE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getBaseName().hashCode();
    hash = (37 * hash) + QUALIFIED_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getQualifiedName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.kythe.proto.SymbolInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.kythe.proto.SymbolInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Contains symbol information for Kythe graph nodes.
   * </pre>
   *
   * Protobuf type {@code kythe.proto.common.SymbolInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kythe.proto.common.SymbolInfo)
      com.google.devtools.kythe.proto.SymbolInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_SymbolInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_SymbolInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.kythe.proto.SymbolInfo.class, com.google.devtools.kythe.proto.SymbolInfo.Builder.class);
    }

    // Construct using com.google.devtools.kythe.proto.SymbolInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      baseName_ = "";

      qualifiedName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.kythe.proto.Common.internal_static_kythe_proto_common_SymbolInfo_descriptor;
    }

    public com.google.devtools.kythe.proto.SymbolInfo getDefaultInstanceForType() {
      return com.google.devtools.kythe.proto.SymbolInfo.getDefaultInstance();
    }

    public com.google.devtools.kythe.proto.SymbolInfo build() {
      com.google.devtools.kythe.proto.SymbolInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.devtools.kythe.proto.SymbolInfo buildPartial() {
      com.google.devtools.kythe.proto.SymbolInfo result = new com.google.devtools.kythe.proto.SymbolInfo(this);
      result.baseName_ = baseName_;
      result.qualifiedName_ = qualifiedName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.kythe.proto.SymbolInfo) {
        return mergeFrom((com.google.devtools.kythe.proto.SymbolInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.kythe.proto.SymbolInfo other) {
      if (other == com.google.devtools.kythe.proto.SymbolInfo.getDefaultInstance()) return this;
      if (!other.getBaseName().isEmpty()) {
        baseName_ = other.baseName_;
        onChanged();
      }
      if (!other.getQualifiedName().isEmpty()) {
        qualifiedName_ = other.qualifiedName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.kythe.proto.SymbolInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.kythe.proto.SymbolInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object baseName_ = "";
    /**
     * <pre>
     * The base un-qualified name for a node.
     * </pre>
     *
     * <code>string base_name = 1;</code>
     */
    public java.lang.String getBaseName() {
      java.lang.Object ref = baseName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The base un-qualified name for a node.
     * </pre>
     *
     * <code>string base_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBaseNameBytes() {
      java.lang.Object ref = baseName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The base un-qualified name for a node.
     * </pre>
     *
     * <code>string base_name = 1;</code>
     */
    public Builder setBaseName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      baseName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The base un-qualified name for a node.
     * </pre>
     *
     * <code>string base_name = 1;</code>
     */
    public Builder clearBaseName() {
      
      baseName_ = getDefaultInstance().getBaseName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The base un-qualified name for a node.
     * </pre>
     *
     * <code>string base_name = 1;</code>
     */
    public Builder setBaseNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      baseName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object qualifiedName_ = "";
    /**
     * <pre>
     * The fully qualified name for a node.
     * </pre>
     *
     * <code>string qualified_name = 2;</code>
     */
    public java.lang.String getQualifiedName() {
      java.lang.Object ref = qualifiedName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        qualifiedName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified name for a node.
     * </pre>
     *
     * <code>string qualified_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQualifiedNameBytes() {
      java.lang.Object ref = qualifiedName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qualifiedName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified name for a node.
     * </pre>
     *
     * <code>string qualified_name = 2;</code>
     */
    public Builder setQualifiedName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      qualifiedName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified name for a node.
     * </pre>
     *
     * <code>string qualified_name = 2;</code>
     */
    public Builder clearQualifiedName() {
      
      qualifiedName_ = getDefaultInstance().getQualifiedName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified name for a node.
     * </pre>
     *
     * <code>string qualified_name = 2;</code>
     */
    public Builder setQualifiedNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      qualifiedName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kythe.proto.common.SymbolInfo)
  }

  // @@protoc_insertion_point(class_scope:kythe.proto.common.SymbolInfo)
  private static final com.google.devtools.kythe.proto.SymbolInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.kythe.proto.SymbolInfo();
  }

  public static com.google.devtools.kythe.proto.SymbolInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SymbolInfo>
      PARSER = new com.google.protobuf.AbstractParser<SymbolInfo>() {
    public SymbolInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SymbolInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SymbolInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SymbolInfo> getParserForType() {
    return PARSER;
  }

  public com.google.devtools.kythe.proto.SymbolInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

